spring.application.name=lumental
fastapi.analysis.base-url=https://fastapi-analysis-921348145792.asia-northeast3.run.app
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORT:8080}
spring.autoconfigure.exclude=\
com.google.cloud.spring.autoconfigure.pubsub.GcpPubSubAutoConfiguration,\
com.google.cloud.spring.autoconfigure.core.GcpContextAutoConfiguration